### PR TITLE
Describe how to get a fully automated setup

### PR DESCRIPTION
**Pull request by pmorch**
Just updates to README.md - could be moved to another file if you'd like.

### CODE REVIEW

**Comment by nbdd0121** [comment]
Thanks! I wouldn't put it directly under `C:\Program Files` though. Perhaps the instruction could be more clear that you can put it in whatever location you want, and you can use the one in `%USERPROFILE%/.cargo` if you want?

**Comment by pmorch** [comment]
I totally understand. I'll change the default paths to be the ones where it gets built.

**Comment by pmorch** [comment]
Actually, is like to avoid installing the rust tool chain... You write:

> The binary will be installed to ~/.cargo/bin/x11-over-vsock and %USERPROFILE%\.cargo\bin\x11-over-vsock.exe

Does rust under WSL2 build both of these? Then I'll just use these as the paths in the description.

**Comment by pmorch** [comment]
Wups, hit close by mistake...

**Comment by nbdd0121** [comment]
> Does rust under WSL2 build both of these? Then I'll just use these as the paths in the description.

No, actually the Windows toolchain is needed to build the Windows executable. Do you think it'll be better to suggest users to download artifacts from pipeline as the first option rather than build themselves?

**Comment by pmorch** [comment]
Depends on the level of paranoia.. 😂 I think most of us will just download
if both options are promoted equally.

**Comment by pmorch** [comment]
I just force-pushed pmorch:master to get a single commit containing the updated Installation chapter, incorporating the changes from issue #2. The original PR and the new changes are in this branch for reference: https://github.com/pmorch/x11-over-vsock/tree/old-installation-pr

**Comment by pmorch** [comment]
I have now run this setup for 13 days without incident. I'm confident that issue #2 has been resolved and that this description now leads to something that is stable.

**Pull request merged**
